# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mensario}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Javier Aranda", "Juan Antonio Galisteo"]
  s.date = %q{2011-06-06}
  s.description = %q{This gem allow us to send, check status and destroy sms using the Mensario service api}
  s.email = ["jaranda@nosolosoftware.biz", "jgalisteo@nosolosoftware.biz"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "COPYING",
    "README.markdown",
    "VERSION",
    "lib/mensario.rb",
    "lib/mensario/api_exception.rb",
    "lib/mensario/exception.rb",
    "lib/mensario/http_exception.rb",
    "mensario.gemspec"
  ]
  s.homepage = %q{http://github.com/nosolosoftware/mensario}
  s.licenses = ["GPL-3"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Wrapper around Mensario API}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<xml-simple>, ["~> 1.0.15"])
      s.add_runtime_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_development_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<rdiscount>, ["~> 1.6.8"])
    else
      s.add_dependency(%q<xml-simple>, ["~> 1.0.15"])
      s.add_dependency(%q<yard>, ["~> 0.7.1"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
      s.add_dependency(%q<rake>, ["~> 0.8.7"])
      s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
    end
  else
    s.add_dependency(%q<xml-simple>, ["~> 1.0.15"])
    s.add_dependency(%q<yard>, ["~> 0.7.1"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.0"])
    s.add_dependency(%q<rake>, ["~> 0.8.7"])
    s.add_dependency(%q<cucumber>, ["~> 0.10.2"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<rdiscount>, ["~> 1.6.8"])
  end
end

