module Mensario
  module Status
    OK = 'OK'
    KO_DIS_SERV = 'KO-DIS-SERV'
    KO_INT_ERR = 'KO-INT-ERR'
    KO_INV_TASK = 'KO-INV-TASK'
    KO_INV_XML = 'KO-INV-XML'
    KO_INV_AUTH = 'KO-INV-AUTH'
    KO_BLK_LIC = 'KO-BLK-LIC'
    KO_EXP_LIC = 'KO-EXP-LIC'
    KO_INV_TZ = 'KO-INV-TZ'
    KO_INV_SINT = 'KO-INV-SINT'
    KO_INV_PHON = 'KO-INV-PHON'
    KO_INV_CODE = 'KO-INV-CODE'
    KO_EXC_AMNT = 'KO-EXC-AMNT'
    KO_INV_TIME = 'KO-INV-TIME'
    KO_UNK_REQU = 'KO-UNK-REQU'
    KO_UNK_MSGS = 'KO-UNK-MSGS'
  end
end
